// Copyright (C) 2020 Inderjit Gill <email@indy.io>

// This file is part of Rona

// Rona is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Rona is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#ifndef TILESET_H
#define TILESET_H

typedef enum {
  TS_Block = 0,

  TS_Hero,
  TS_Archer,
  TS_Warrior,
  TS_Cleric,
  TS_Rogue,
  TS_Sorcerer,
  TS_Mage,
  TS_King,
  TS_Boy,
  TS_Dog,
  TS_Toddler,
  TS_Fatman,
  TS_Ghost,

  TS_DebugChecker,
  TS_DebugBlank,
  TS_DebugFilled,
  TS_Debug4Corners,

  TS_BorderTop,
  TS_BorderTopRight,
  TS_BorderRight,
  TS_BorderBottomRight,
  TS_BorderBottom,
  TS_BorderLeft,
  TS_BorderBottomLeft,
  TS_BorderTopLeft,

  TS_Heroine,
  TS_FemaleArcher,
  TS_FemaleWarrior,
  TS_FemaleCleric,
  TS_FemaleRogue,
  TS_Sorceress,
  TS_FemaleMage,
  TS_Queen,
  TS_Girl,
  TS_Cat,
  TS_FemaleToddler,
  TS_Fatwoman,
  TS_FemaleGhost,

  TS_Floor,

  TS_OldMan,
  TS_Patches,
  TS_Hopolite,
  TS_MagicThing1,
  TS_MagicOldMan,
  TS_MagicThing2,
  TS_Mermaid,

  TS_BlockSub0,
  TS_BlockSub1,
  TS_BlockSub2,
  TS_BlockPat1,
  TS_BlockPat2,

  TS_FaceNeutral,
  TS_FaceSmile,
  TS_FaceJoy,
  TS_FaceSad,
  TS_FaceCry,
  TS_FaceAngry,
  TS_FaceShout,
  TS_FaceTaste,
  TS_FaceEat,
  TS_FaceSleep,
  TS_FacePatches,
  TS_FaceGlasses,

  TS_Rat,
  TS_Bat,
  TS_Caterpillar,
  TS_Spider,
  TS_Scorpion,
  TS_Snail,
  TS_Snake,
  TS_Dingo,
  TS_Panther,
  TS_Bear,
  TS_Drake,
  TS_Dragon,
  TS_Unicorn,

  TS_Gremlin,
  TS_Ogre,
  TS_Troll,
  TS_Minotaur,

  TS_Ghoul,
  TS_PhantomHand,
  TS_Skeleton,
  TS_SkeletonWarrior,
  TS_SkeletonDeath,
  TS_EnemyGhost,
  TS_GhostSpirit,
  TS_Phantom,

  TS_JellyFish,
  TS_Octopus,
  TS_Eyeball,
  TS_MidgetThief,
  TS_MidgetSprite,
  TS_WalkingChest,
  TS_Robot,
  TS_RobotBrute,

  TS_Brick1,
  TS_Brick2,
  TS_Brick3,
  TS_Ground1,
  TS_Ground2,
  TS_Ground3,
  TS_PressurePadPrimed,
  TS_PressurePadActivated,
  TS_PointyGround,
  TS_FloorSwitch,
  TS_StairsDown,
  TS_StairsUp,
  TS_DoorClosed,
  TS_DoorOpen,
  TS_FlamingTurd,
  TS_SquashedTurd,

  TS_Gravestone,
  TS_Sign,
  TS_Stool,
  TS_Cupboard,
  TS_Bookshelf,
  TS_Table,
  TS_Bed,

  TS_WallHorizontal,
  TS_WallVertical,
  TS_WallHorizontalPoint,
  TS_WallTLCorner,
  TS_WallTRCorner,
  TS_WallBLCorner,
  TS_WallBRCorner,
  TS_WallTeeLeft,
  TS_WallTeeRight,
  TS_WallTeeDown,
  TS_WallTeeUp,
  TS_WallCross,

  TS_WeakFloor,
  TS_SpiderWeb,
  TS_TrapPrimed,
  TS_TrapActivated,
  TS_SpikesOnFloor,
  TS_SpikesInFloor,
  TS_Grate,
  TS_Wat,
  TS_FloorSwitchPrimed,
  TS_FloorSwitchActivated,
  TS_LeverLeft,
  TS_LeverRight,

  TS_MapPlain1,
  TS_MapPlain2,
  TS_MapPlain3,
  TS_MapTree1,
  TS_MapTree2,
  TS_MapTree3,
  TS_MapWater,
  TS_MapHouses,
  TS_MapCave,
  TS_MapHouse,
  TS_MapCastle,
  TS_MapCaravan,
  TS_MapShip,

  TS_Torch,
  TS_Lantern,
  TS_Spade,
  TS_Pickaxe,
  TS_Rope,
  TS_Bomb,
  TS_ChestClosed,
  TS_ChestOpen,
  TS_Vase,
  TS_VaseBroken,
  TS_DoorKey,
  TS_ChestKey,
  TS_Pouch,
  TS_Coins,
  TS_Biscuit,
  TS_Rupee,

  TS_Pearl,
  TS_SkullAndBones,
  TS_Bone,
  TS_Tongue,
  TS_MonsterSkull,

  TS_FoodDrumStick,
  TS_FoodSteak,
  TS_FoodKebab,
  TS_FoodFish,
  TS_FoodFriedEgg,
  TS_FoodBreadSlice,
  TS_FoodEgg,
  TS_FoodQuiche,
  TS_FoodApple,
  TS_FoodPumpkin,
  TS_FoodTurnip,
  TS_FoodBasil,
  TS_FoodFlower,
  TS_FoodMushroom,
  TS_FoodSweet,
  TS_FoodCake,

  TS_Beer,
  TS_Pot,
  TS_Jug,
  TS_SmallJar,
  TS_LargeJar,
  TS_ExpensiveJar,

  TS_WeaponDagger,
  TS_WeaponSword,
  TS_WeaponAxe,
  TS_WeaponPickaxe,
  TS_WeaponStaff,
  TS_WeaponClub,
  TS_WeaponMallet,
  TS_WeaponShield1,
  TS_WeaponShield2,
  TS_WeaponBow,
  TS_WeaponArrows,
  TS_ArmourHelmet1,
  TS_ArmourHelmet2,
  TS_WizardHat,
  TS_ArmourGloves,
  TS_ArmourBracelets,

  TS_ClothesBoots,
  TS_ClothesTrousers,
  TS_ClothesBelt,
  TS_ClothesTop1,
  TS_ClothesTop2,
  TS_ClothesTop3,
  TS_ClothesHood,
  TS_ClothesRing,
  TS_ClothesPendant,
  TS_ClothesCrown,
  TS_ClothesGlasses,

  TS_MagickWand,
  TS_MagickWandJeweled,
  TS_MagickWandSkulled,
  TS_MagickGlobe,
  TS_MagickPendant,
  TS_MagickSkull,
  TS_MagickScroll1,
  TS_MagickScroll2,
  TS_MagickBook,
  TS_MagickPedestal,
  TS_MagickCouldron,
  TS_MagickHex1,
  TS_MagickHex2,
  TS_MagickHexHand,
  TS_MagickWat,

  TS_MusicMandolin,
  TS_MusicHarp,
  TS_MusicPanFlute,
  TS_MusicBell,
  TS_MusicXylophone,
  TS_MusicDrum,

  TS_At,
  TS_DontUse1,
  TS_DontUse2,
  TS_Plus,
  TS_Cross,
  TS_Heart,
  TS_Star,
  TS_Sun,
  TS_Moon,
  TS_Bullseye,
  TS_Warning,
  TS_Music,
  TS_Fire,
  TS_Frost,
  TS_Rain,
  TS_Lightning,

  TS_Whirl,
  TS_Bubble,
  TS_Sleep,
  TS_Skull,
  TS_Arms,
  TS_Shield,
  TS_Hourglass,
  TS_North,
  TS_NorthEast,
  TS_East,
  TS_SouthEast,
  TS_South,
  TS_SouthWest,
  TS_West,
  TS_NorthWest,

  TS_NumTilesetSprites
} TilesetSprite;

// image_dim and sprite_dim should be valid
void tileset_calc_uv_units(Tileset* tileset);
Vec2 tileset_get_uv(Tileset* tileset, TilesetSprite sprite);
Vec2 tileset_get_uv_char(Tileset* tileset, char c);
void tileset_add_char(RenderStruct* render_struct, char c, Vec2* pos, Vec4* fg, Vec4* bg);
#endif /* TILESET_H  */
